FROM node:18-alpine

# Create app directory
WORKDIR /usr/src/app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy the rest of the app
COPY . .

# Install nodemon globally
RUN npm install -g nodemon

# Expose backend port
EXPOSE 8080

# Start the app in dev mode
CMD ["nodemon", "app.js"]
