name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      FRONTEND_IMAGE: nyigoro/frontend
      BACKEND_IMAGE: nyigoro/backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # --- 🔍 Run Backend Tests ---
      - name: Install backend dependencies
        run: npm install
        working-directory: ./backend

      - name: Run backend tests
        run: npm test
        working-directory: ./backend

      # --- 🧼 Run Frontend Lint ---
      - name: Install frontend dependencies
        run: npm install
        working-directory: ./frontend

      - name: Run frontend lint
        run: npm run lint
        working-directory: ./frontend

      # --- 🐳 Build & Push Docker Images ---
      - name: Build & Push Frontend Image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ env.FRONTEND_IMAGE }}:latest

      - name: Build & Push Backend Image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ env.BACKEND_IMAGE }}:latest

      # --- 🚀 Trigger Deploy to Render ---
      - name: Trigger Render Deploy (Frontend)
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_FRONTEND }}

      - name: Trigger Render Deploy (Backend)
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_BACKEND }}
